// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_33TZcNZU8fEGZYjtUuPCsMql9uRBVPg',
    appId: '1:49834426101:web:d13c2b6d3099513fd00fbc',
    messagingSenderId: '49834426101',
    projectId: 'fluttertest-ec275',
    authDomain: 'fluttertest-ec275.firebaseapp.com',
    storageBucket: 'fluttertest-ec275.appspot.com',
    measurementId: 'G-YNB0QJM6MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1Yye9RILKjea68VTzplZkor5C7plAbw',
    appId: '1:49834426101:android:1d96596b3e394002d00fbc',
    messagingSenderId: '49834426101',
    projectId: 'fluttertest-ec275',
    storageBucket: 'fluttertest-ec275.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfp2lgK3m2jfEALn4FaSE7nDAELBlzp1M',
    appId: '1:49834426101:ios:5b885b79a61d096ed00fbc',
    messagingSenderId: '49834426101',
    projectId: 'fluttertest-ec275',
    storageBucket: 'fluttertest-ec275.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfp2lgK3m2jfEALn4FaSE7nDAELBlzp1M',
    appId: '1:49834426101:ios:5b885b79a61d096ed00fbc',
    messagingSenderId: '49834426101',
    projectId: 'fluttertest-ec275',
    storageBucket: 'fluttertest-ec275.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_33TZcNZU8fEGZYjtUuPCsMql9uRBVPg',
    appId: '1:49834426101:web:c52b985209be6ea6d00fbc',
    messagingSenderId: '49834426101',
    projectId: 'fluttertest-ec275',
    authDomain: 'fluttertest-ec275.firebaseapp.com',
    storageBucket: 'fluttertest-ec275.appspot.com',
    measurementId: 'G-R3BR1GGXBW',
  );
}
